repos:
-   repo: local
    hooks:
    -   id: PreCommit
        name: Pre Commit
        entry: "python setup.py pre_commit --"
        language: system
        types: [python]
        stages: [commit]
        pass_filenames: false
        always_run: true