name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    matrix:
      include:
          - python-version: "3.10"
          - python-version: "3.10.3"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Install developer dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Test with pytest
      run: |
        pytest tests
